# Generated by Django 4.2.7 on 2023-11-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pin', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('batch_no', models.IntegerField(default=21124)),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
