# Generated by Django 6.0.2 on 2026-02-17 07:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_pin', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('age', models.IntegerField()),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('batch_no', models.IntegerField(default=21124)),
                ('college', models.CharField(default='T.R.R. College of Technology', max_length=100)),
                ('cgpa', models.FloatField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
