# Generated by Django 4.2.7 on 2023-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0002_alter_student_college_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_pin',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
