# Generated by Django 4.2.7 on 2024-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0003_alter_student_student_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_pin',
            field=models.PositiveIntegerField(),
        ),
    ]
