# Generated by Django 4.2.7 on 2024-02-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0004_alter_student_student_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pin',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
