# Generated by Django 4.2.7 on 2024-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0006_alter_student_admission_date_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
