# Generated by Django 4.2.7 on 2024-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0007_alter_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
