# Generated by Django 6.0.2 on 2026-02-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
